tomcat embedded

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -2,7 +2,7 @@
 set -e
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
-source ${OPENSHIFT_TOMCAT_DIR}/bin/util
+source ${OPENSHIFT_CBP_DIR}/bin/util
 
 if ! [ $# -eq 1 ]
 then
@@ -10,9 +10,9 @@ then
     exit 1
 fi
 
-source ${OPENSHIFT_TOMCAT_DIR}/bin/util
+source ${OPENSHIFT_CBP_DIR}/bin/util
 
-TOMCAT_PID_FILE="${OPENSHIFT_TOMCAT_DIR}/run/tomcat.pid"
+CBP_PID_FILE="${OPENSHIFT_CBP_DIR}/run/tomcat.pid"
 
 # Kill the process given by $1 and its children
 killtree() {
@@ -27,8 +27,8 @@ killtree() {
 # Check if the tomcatas process is running
 isrunning() {
     # Check for running app
-    if [ -f "$TOMCAT_PID_FILE" ]; then
-      jbpid=$(cat $TOMCAT_PID_FILE);
+    if [ -f "$CBP_PID_FILE" ]; then
+      jbpid=$(cat $CBP_PID_FILE);
       running=`/bin/ps --no-headers --pid $jbpid`
       if test -n "$running";
       then
@@ -44,8 +44,8 @@ function ishttpup() {
     let count=0
     while [ ${count} -lt 24 ]
     do
-        if /usr/sbin/lsof -P -n -i "@${OPENSHIFT_TOMCAT_IP}:${OPENSHIFT_TOMCAT_HTTP_PORT}" | grep "(LISTEN)" > /dev/null; then
-            echo "Found ${OPENSHIFT_TOMCAT_IP}:${OPENSHIFT_TOMCAT_HTTP_PORT} listening port"
+        if /usr/sbin/lsof -P -n -i "@${OPENSHIFT_CBP_IP}:${OPENSHIFT_CBP_HTTP_PORT}" | grep "(LISTEN)" > /dev/null; then
+            echo "Found ${OPENSHIFT_CBP_IP}:${OPENSHIFT_CBP_HTTP_PORT} listening port"
             return 0
         fi
         let count=${count}+1
@@ -60,14 +60,14 @@ function start_app() {
         echo "The tomcat cartridge is already running" 1>&2
     else
         # Start
-        export CATALINA_HOME=$OPENSHIFT_TOMCAT_DIR
-        export CATALINA_BASE=$OPENSHIFT_TOMCAT_DIR
-        export CATALINA_TMPDIR=${OPENSHIFT_TOMCAT_DIR}/tmp
+        export CATALINA_HOME=$OPENSHIFT_CBP_DIR
+        export CATALINA_BASE=$OPENSHIFT_CBP_DIR
+        export CATALINA_TMPDIR=${OPENSHIFT_CBP_DIR}/tmp
         
-        ${OPENSHIFT_TOMCAT_DIR}/bin/tomcat start > ${OPENSHIFT_TOMCAT_DIR}/logs/tomcat.log 2>&1 &
+        ${OPENSHIFT_CBP_DIR}/bin/tomcat start > ${OPENSHIFT_CBP_DIR}/logs/tomcat.log 2>&1 &
         PROCESS_ID=$!
         
-        echo $PROCESS_ID > $TOMCAT_PID_FILE
+        echo $PROCESS_ID > $CBP_PID_FILE
         if ! ishttpup; then
             echo "Timed out waiting for http listening port"
             exit 1
@@ -78,12 +78,12 @@ function start_app() {
 function stop_app() {
     if ! isrunning; then
         echo "The tomcat cartridge is already stopped" 1>&2
-    elif [ -f "$TOMCAT_PID_FILE" ]; then
-        pid=$(cat $TOMCAT_PID_FILE);
+    elif [ -f "$CBP_PID_FILE" ]; then
+        pid=$(cat $CBP_PID_FILE);
         echo "Sending SIGTERM to tomcat:$pid ..." 1>&2
         killtree $pid
     else 
-        echo "Failed to locate TOMCAT PID File" 1>&2
+        echo "Failed to locate CBP PID File" 1>&2
     fi
 }
 
@@ -91,24 +91,24 @@ function threaddump() {
     if ! isrunning; then
         echo "The tomcat cartridge is stopped"
         exit 1
-    elif [ -f "$TOMCAT_PID_FILE" ]; then
-        pid=$(cat $TOMCAT_PID_FILE);
+    elif [ -f "$CBP_PID_FILE" ]; then
+        pid=$(cat $CBP_PID_FILE);
         java_pid=`ps h --ppid $pid -o '%p'`
         kill -3 $java_pid
         client_result "Success"
         client_result ""
         client_result "The thread dump file will be available via: rhc tail $OPENSHIFT_APP_NAME -f */logs/catalina.out -o '-n 250'"
     else 
-        echo "Failed to locate TOMCAT PID File"
+        echo "Failed to locate CBP PID File"
     fi
 }
 
 # Clean up any log files
 function tidy() {
-  client_message "Emptying log dir: $OPENSHIFT_TOMCAT_LOG_DIR"
+  client_message "Emptying log dir: $OPENSHIFT_CBP_LOG_DIR"
   shopt -s dotglob
-  rm -rf $OPENSHIFT_TOMCAT_LOG_DIR/*
-  rm -rf $OPENSHIFT_TOMCAT_DIR/tmp/*
+  rm -rf $OPENSHIFT_CBP_LOG_DIR/*
+  rm -rf $OPENSHIFT_CBP_DIR/tmp/*
 }
 
 # Reconstruct JAVA_HOME and PATH based on the current version/marker selection
@@ -145,17 +145,17 @@ case "$1" in
             exit 0
         fi
 
-        client_result tailing "$OPENSHIFT_TOMCAT_DIR/logs/catalina.out"
+        client_result tailing "$OPENSHIFT_CBP_DIR/logs/catalina.out"
         client_result "------ Tail of Tomcat catalina.out ------"
-        client_result $(tail "$OPENSHIFT_TOMCAT_DIR/logs/catalina.out")
+        client_result $(tail "$OPENSHIFT_CBP_DIR/logs/catalina.out")
         exit 0
     ;;
     build)
-        ${OPENSHIFT_TOMCAT_DIR}/bin/build
+        ${OPENSHIFT_CBP_DIR}/bin/build
         exit 0
     ;;
     deploy)
-        ${OPENSHIFT_TOMCAT_DIR}/bin/deploy
+        ${OPENSHIFT_CBP_DIR}/bin/deploy
         exit 0
     ;;
     update-configuration)
